from automata.fa.Moore import Moore
import sys, os

from myerror import MyError

error_handler = MyError('LexerErrors')

global check_cm
global check_key

moore = Moore(
    # Estados
    ['q0', 'intI', 'intN', 'intT', 'int', 'elseE', 'elseL', 'elseS', 'elseE2', 'else', 
     'voidV', 'voidO', 'voidI', 'voidD', 'void', 'returnR', 'returnE', 'returnT', 'return', 
     'floatF', 'floatL', 'floatO', 'floatT', 'float', 'mais', 'menos', 'vezes', 'dividir', 
     'menor', 'menorIgual', 'maior', 'maiorIgual', 'igual', 'diferente', 'parentesesEsquerda', 
     'parentesesDireita', 'colchetesEsquerda', 'colchetesDireita', 'chavesEsquerda', 
     'chavesDireita', 'atribuicao', 'pontoVirgula', 'virgula','number','idMais','idMenos','idDividir',
     'idMaior','idMenor','idEspaco','idChaveEsquerda','idChaveDireita','idColcheteDireita','idVezes',
     'idVirgula','idPontoVirgula','igualIntermed'],

    # Alfabeto
  # Alfabeto
[
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',  # letras minúsculas
        ' ', '\n', '+', '-', '*', '/', '<', '=', '>', '(', ')', '[', ']', '{', '}', ';', ','  # símbolos especiais
    ],

    # Saídas
    ['IF', 'ELSE', 'INT', 'FLOAT', 'RETURN', 'VOID', 'WHILE', 'PLUS', 'MINUS', 'TIMES', 'DIVIDE', 'LESS', 'LESS_EQUAL', 'GREATER', 'GREATER_EQUAL', 'EQUALS', 'DIFFERENT', 'LPAREN', 'RPAREN', 
     'LBRACKETS', 'RBRACKETS', 'LBRACES', 'RBRACES', 'ATTRIBUTION', 'SEMICOLON', 'COMMA'],

   # Transições
    {
        'q0': {
            'i': 'id',
            'e': 'id',
            'v': 'id',
            'r': 'id',
            'f': 'id',
            'w': 'id',
            '+': 'mais',
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',
            '_': 'id',  
            'a': 'id',  
            'b': 'id',
            'c': 'id',
            'd': 'id',
            'g': 'id',
            'h': 'id',
            'j': 'id',
            'k': 'id',
            'l': 'id',
            'm': 'id',
            'n': 'id',
            'o': 'id',
            'p': 'id',
            'q': 'id',
            's': 'id',
            't': 'id',
            'u': 'id',
            'x': 'id',
            'y': 'id',
            'z': 'id',
            ' ': 'q0',
            '\n': 'q0',
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
        },

        # Transições para "int"
        'intI': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'iF', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'intN', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'intN': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'intT', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'intT': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },

        #Transições para "if"
        'iF': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'idEspaco',  
            '\n': 'idEspaco',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'igualIntermed',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        # Transições para "id"
        'id': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'iF', 'g': 'id', 'h': 'whileH',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'elseL', 'm': 'id', 'n': 'intN', 'o': 'voidO', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'idEspaco',  
            '\n': 'idEspaco',  
             '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idEspaco',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',              
    },
    'idEspaco': {
    'a': 'atribuicaoId', 'b': 'atribuicaoId', 'c': 'atribuicaoId', 'd': 'atribuicaoId', 'e': 'atribuicaoId', 'f': 'atribuicaoId', 'g': 'atribuicaoId', 'h': 'atribuicaoId',
'i': 'atribuicaoId', 'j': 'atribuicaoId', 'k': 'atribuicaoId', 'l': 'atribuicaoId', 'm': 'atribuicaoId', 'n': 'atribuicaoId', 'o': 'atribuicaoId', 'p': 'atribuicaoId',
'q': 'atribuicaoId', 'r': 'atribuicaoId', 's': 'atribuicaoId', 't': 'atribuicaoId', 'u': 'atribuicaoId', 'v': 'atribuicaoId', 'w': 'atribuicaoId', 'x': 'atribuicaoId',
'y': 'atribuicaoId', 'z': 'atribuicaoId',   
    '0': 'atribuicaoNumber', '1': 'atribuicaoNumber', '2': 'atribuicaoNumber', '3': 'atribuicaoNumber', '4': 'atribuicaoNumber', '5': 'atribuicaoNumber', 
    '6': 'atribuicaoNumber', '7': 'atribuicaoNumber', '8': 'atribuicaoNumber', '9': 'atribuicaoNumber',  
    '_': 'q0', 
    ' ': 'q0',  
    '\n': 'q0',  
    '+': 'mais',  
    '-': 'menos',
    '*': 'vezes',
    '/': 'dividir',
    '<': 'menor',
    '=': 'igualIntermed',
    '>': 'maior',
    '(': 'parentesesEsquerda',
    ')': 'parentesesDireita',
    '[': 'colcheteEsquerda',
    ']': 'colcheteeDireita',
    '{': 'chaveEsquerda',
    '}': 'chaveDireita',
    ';': 'pontoVirgula',
    ',': 'virgula', 
},

    'idMais': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idMenos': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',   
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idVezes': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idDividir': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idMenor': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idIgual': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idMaior': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',               
    },
    'idParentesesEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                 
    },
    'idParentesesDireita': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                   
    },
    
    'idVirgula': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',   
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                   
    },
    'idPontoVirgula': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                    
    },
    'idColcheteEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',    
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                    
    },
    'idColcheteDireita': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDireita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                    
    },
    'idChaveDireita': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                    
    },
    'idChaveEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',                    
    },


        # Transições para "else"
        'elseE': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'elseL', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'returnT', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'elseL': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'floatO', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'elseS', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'elseS': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE2', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'elseE2': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },

        # Transições para "void"
        'voidV': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'voidO', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'voidO': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'voidI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'voidI': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'voidD', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'voidD': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            '\n': 'q0',
            ' ': 'q0',
        },

        # Transições para "return"
        'returnR': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'returnE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'returnE': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'returnT', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'returnT': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'returnU', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'returnU': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR2', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'returnR2': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'returnN', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'idMais',  
            '-': 'idMenos',
            '*': 'idVezes',
            '/': 'idDividir',
            '<': 'idMenor',
            '=': 'idIgual',
            '>': 'idMaior',
            '(': 'idParentesesEsquerda',
            ')': 'idParentesesDireita',
            '[': 'idColcheteEsquerda',
            ']': 'idColcheteeDireita',
            '{': 'idChaveEsquerda',
            '}': 'idChaveDireita',
            ';': 'idPontoVirgula',
            ',': 'idVirgula',    
            ' ': 'q0',
            '\n': 'q0',
        },
        'returnN': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },

        # Transições para "float"
        'floatF': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'floatL', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'floatL': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'floatO', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'floatO': {
            'a': 'floatA', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'floatA': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'floatT', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'floatT': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },

        # Transições para "while"
        'whileW': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'whileH',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'whileH': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'whileI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'whileI': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'whileL', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'whileL': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'whileE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'whileE': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0', 
        },

        # Transições para operadores
        'mais': {
'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'menos': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'vezes': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'dividir': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'menor': {
            '=': 'menorIgual',
            ' ': 'q0',
            '\n': 'q0',
        },
        'menorIgual': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'maior': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'maiorIgual': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
            ' ': 'q0',
            '\n': 'q0',
        },
        'igual': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'igualIntermed': {
            'a': 'igualId', 'b': 'igualId', 'c': 'igualId', 'd': 'igualId', 'e': 'igualId', 'f': 'igualId', 'g': 'igualId', 'h': 'igualId',
            'i': 'igualId', 'j': 'igualId', 'k': 'igualId', 'l': 'igualId', 'm': 'igualId', 'n': 'idIgual', 'o': 'igualId', 'p': 'idigualIdIgual',
            'q': 'igualId', 'r': 'idigualIdIgual', 's': 'idigualIdIgual', 't': 'iigualIddIgual', 'u': 'igualId', 'v': 'idIgigualIdual', 'w': 'idigualIdIgual', 'x': 'atribuicao',
            'y': 'igualId', 'z': 'igualId',  
            '0': 'igualNumber', '1': 'igualNumber', '2': 'igualNumber', '3': 'igualNumber', '4': 'igualNumber', '5': 'igualNumber', '6': 'igualNumber', '7': 'igualNumber', '8': 'igualNumber', '9': 'igualNumber',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'igual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'igualId': {
           'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id', 
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'igualNumber': {
           'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id', 
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'diferente': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'diferenteIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'diferenteIgual': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'parentesesEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   

            ' ': 'q0',
            '\n': 'q0',
        },
        'parentesesDireita': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'colcheteEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'colcheteDireita': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'chaveEsquerda': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'id', '1': 'id', '2': 'id', '3': 'id', '4': 'id', '5': 'id', '6': 'id', '7': 'id', '8': 'id', '9': 'id',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula', 
            ' ': 'q0',
            '\n': 'q0',
        },
        'chaveDireita': {
           'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'floatF', 'g': 'id', 'h': 'id',
            'i': 'intI', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'returnR', 's': 'id', 't': 'id', 'u': 'id', 'v': 'voidV', 'w': 'whileW', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
        },
        'atribuicao': {
    'a': 'atribuicaoId', 'b': 'atribuicaoId', 'c': 'atribuicaoId', 'd': 'atribuicaoId', 'e': 'atribuicaoId', 'f': 'atribuicaoId', 'g': 'atribuicaoId', 'h': 'atribuicaoId',
    'i': 'atribuicaoId', 'j': 'atribuicaoId', 'k': 'atribuicaoId', 'l': 'atribuicaoId', 'm': 'atribuicaoId', 'n': 'atribuicaoId', 'o': 'atribuicaoId', 'p': 'atribuicaoId',
    'q': 'atribuicaoId', 'r': 'atribuicaoId', 's': 'atribuicaoId', 't': 'atribuicaoId', 'u': 'atribuicaoId', 'v': 'atribuicaoId', 'w': 'atribuicaoId', 'x': 'atribuicaoId',
    'y': 'atribuicaoId', 'z': 'atribuicaoId',  
    '0': 'atribuicaoNumber', '1': 'atribuicaoNumber', '2': 'atribuicaoNumber', '3': 'atribuicaoNumber', '4': 'atribuicaoNumber', '5': 'atribuicaoNumber', '6': 'atribuicaoNumber', '7': 'atribuicaoNumber', '8': 'atribuicaoNumber', '9': 'atribuicaoNumber',  
            '_': 'id', 
            ' ': 'atribuicao',  
            '\n': 'atribuicao',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'id',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'atribuicaoNumber': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'atribuicaoId': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        
        'pontoVirgula': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'virgula': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'elseE', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'atribuicao',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
        'number': {
            'a': 'id', 'b': 'id', 'c': 'id', 'd': 'id', 'e': 'id', 'f': 'id', 'g': 'id', 'h': 'id',
            'i': 'id', 'j': 'id', 'k': 'id', 'l': 'id', 'm': 'id', 'n': 'id', 'o': 'id', 'p': 'id',
            'q': 'id', 'r': 'id', 's': 'id', 't': 'id', 'u': 'id', 'v': 'id', 'w': 'id', 'x': 'id',
            'y': 'id', 'z': 'id',  
            '0': 'number', '1': 'number', '2': 'number', '3': 'number', '4': 'number', '5': 'number', '6': 'number', '7': 'number', '8': 'number', '9': 'number',  
            '_': 'id', 
            ' ': 'q0',  
            '\n': 'q0',  
            '+': 'mais',  
            '-': 'menos',
            '*': 'vezes',
            '/': 'dividir',
            '<': 'menor',
            '=': 'maiorIgual',
            '>': 'maior',
            '(': 'parentesesEsquerda',
            ')': 'parentesesDireita',
            '[': 'colcheteEsquerda',
            ']': 'colcheteeDIreita',
            '{': 'chaveEsquerda',
            '}': 'chaveDireita',
            ';': 'pontoVirgula',
            ',': 'virgula',   
            ' ': 'q0',
            '\n': 'q0',
        },
    },

    'q0',  # Estado inicial

    # Saídas para os estados finais
    {
        'q0': '',
        'intI': '', 'intN': '', 'intT': 'INT\n','iF': 'IF\n','id': '','idParentesesDireita': 'ID\nRPAREN\n','idEspaco': 'ID\n','igualIntermed': '','igualId': 'EQUALS\nID\n','igualNumber': 'EQUALS\nNUMBER\n',
        'atribuicaoNumber': 'ATTRIBUTION\nNUMBER\n','atribuicaoId': 'ATTRIBUTION\nID\n',
        'idParentesesEsquerda': 'ID\nLPAREN\n','idVirgula': 'ID\nCOMMA\n','idPontoVirgula': 'ID\nSEMICOLON\n','idMais': 'ID\nPLUS\n','idMenos': 'ID\nMINUS\n','idVezes': 'ID\nTIMES\n','idDividir': 'ID\nDIVIDE\n','idMenor': 'ID\nLESS\n','idMaior': 'ID\nGREATER\n', 'idColcheteEsquerda': 'ID\nLBRACKETS\n','idColcheteDireita': 'ID\nRBRACKETS\n','idChaveEsquerda': 'ID\nLBRACES\n','idChaveDireita': 'ID\nRBRACES\n','number': 'NUMBER\n','idIgual':'ID\nATTRIBUTION\n',
        'elseE': '', 'elseL': '', 'elseS': '', 'elseE2': 'ELSE\n',
        'voidV': '', 'voidO': '', 'voidI': '', 'voidD': 'VOID\n',
        'returnR': '', 'returnE': '', 'returnT': '', 'returnU': '','returnR2': '', 'returnN': 'RETURN\n',
        'floatF': '', 'floatL': '', 'floatO': '', 'floatA': '', 'floatT': 'FLOAT\n',
        'whileW': '', 'whileH': '', 'whileI': '', 'whileL': '', 'whileE': 'WHILE\n',
        'mais': 'PLUS\n', 'menos': 'MINUS\n', 'vezes': 'TIMES\n', 'dividir': 'DIVIDE\n',
        'menor': 'LESS\n', 'menorIgual': 'LESS_EQUAL\n', 'maior': 'GREATER\n', 'maiorIgual': 'GREATER_EQUAL\n',
        'igual': 'EQUALS\n', 'diferente': 'DIFFERENT\n', 'parentesesEsquerda': 'LPAREN\n',
        'parentesesDireita': 'RPAREN\n', 'colchetesEsquerda': 'LBRACKETS\n', 
        'colchetesDireita': 'RBRACKETS\n', 'chaveEsquerda': 'LBRACES\n', 
        'chaveDireita': 'RBRACES\n', 'atribuicao': '', 'pontoVirgula': 'SEMICOLON\n', 
        'virgula': 'COMMA\n',
    }
)






def main():
    check_cm = False
    check_key = False
    
    for idx, arg in enumerate(sys.argv):
        print("Argument #{} is {}".format(idx, arg))
        aux = arg.split('.')
        if aux[-1] == 'cm':
            check_cm = True
            idx_cm = idx

        if(arg == "-k"):
            check_key = True
    
    print ("No. of arguments passed is ", len(sys.argv))

    if(len(sys.argv) < 3):
        raise TypeError(error_handler.newError(check_key, 'ERR-LEX-USE'))

    if not check_cm:
      raise IOError(error_handler.newError(check_key, 'ERR-LEX-NOT-CM'))
    elif not os.path.exists(sys.argv[idx_cm]):
        raise IOError(error_handler.newError(check_key, 'ERR-LEX-FILE-NOT-EXISTS'))
    else:
        data = open(sys.argv[idx_cm])
        source_file = data.read()

        if not check_cm:
            print("Definição da Máquina")
            print(moore)
            print("Entrada:")
            print(source_file)
            print("Lista de Tokens:")
        
    print(moore.get_output_from_string(source_file))


if __name__ == "__main__":

    try:
        main()
    except Exception as e:
        print(e)
    except (ValueError, TypeError):
        print(e)